version: '2'
services:
    monitoringihm-app:
        image: monitoringihm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://monitoringihm-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=monitoringIhm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=monitoringihm-elasticsearch:9300
        ports:
            - 8080:8080
    monitoringihm-mongodb:
        extends:
            file: mongodb.yml
            service: monitoringihm-mongodb
    monitoringihm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: monitoringihm-elasticsearch
